### ISSUE TITLE
Font selection

### ISSUE THREAD

**Issue by PeterHallengreen** [samuelmr/garmin-abouttime#18]
As the update of june 12, changed the font - I would really appreciate to have the option to choose between the fonts.
I would like to have the option to choose the font that was used before June 12

**Comment by samuelmr** [comment]
Thanks for the feedback!

The previous version used (accidentally) Arial as the font face. I originally chose Andika as the font face (since it has a unique character and good legibility, but at some point, the font resources got replaced with Arial.

Since the custom fonts are used as PNG images embedded in the watch face, it's not feasible to embed multiple fonts and let the user decide. (Many watches wouldn't have enough memory to store both font faces.)

I also received - by email - another complaint about the new font. Not sure whether it was about the font face or the font size. I asked for clarification.

**Comment by samuelmr** [comment]
I see 3 options here:

1. fall back to Arial as the font face (not an open-source font, somewhat boring)
2. keep Andika (not everyone's cup of tea)
3. find yet another font (e.g. Open Sans)

Feel free to voice your opinion in this thread. (This applies to everyone, not just Peter.)

**Comment by Lenniitsch** [comment]
I also preferred the old font, somehow I liked that it looks "boring" as you said. Even after the update, icons and font are too big in my opinion. So if you choose option 1, I don't know if this would scale back the icons and font as well.

**Comment by samuelmr** [comment]
@PeterHallengreen and @Lenniitsch please let me know which language versions you're using. I'll push updates using Noto Sans font to the store.

I'm also thinking about a setting that you could use to choose smaller font and icon size.

**Comment by samuelmr** [comment]
https://github.com/samuelmr/garmin-abouttime/commit/8b13f7d6703067744afefe74f161f31e3c71ae23 adds a setting to choose a smaller font. The font face for all translations (except Chinese, Hebrew, Japanese, and Korean) is now Noto Sans which is pretty plain. The translations are being compiled. I'll start uploading them to the Connect IQ store next week.

**Comment by samuelmr** [comment]
Considering this fixed. Please reopen if needed.
