### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by Abraxas10** [samuelmr/garmin-abouttime#9]
Ideea: would be nice, if the text could be shown in varoius font sizes. In my opinion actually its to small.

**Comment by samuelmr** [comment]
Totally agree. Especially for Venu the font size is much too small. Also the font size for data field is too small for e.g. Fenix series and many other watches with similar screen size.

In theory, ConnectIQ SDK allows device-specific font settings and language-specific translations. However, the font sizes and languages are tied together since fonts are specified as follows:
`  <font id="id_font_small" filename="fonts/andika24.fnt" antialias="true" filter=" %.0123456789ADEFHNSUVZabcefghiklmnorstuvwzÖäöü" />`

The filter is required since otherwise the embedded font consumes too much memory. The filter is based on language. Font size is based on device.

ConnectIQ SDK's built-in resource management is unable to handle language-specific font filters, and I've been forced to create my own build system where each translation is a different app, sharing the common source code.

I have made some experiments with font sizes but haven't yet figured out a way that's compatible with my custom build system.

I'll double my efforts. :-)
